version: 2
jobs:

  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/startmeapp-hackathon-front

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Set docker image tag
          command: |
            SHORT_COMMIT_HASH="$(git rev-parse --short=8 HEAD)"
            if [ $CIRCLE_BRANCH == 'master' ]; then
                BRANCH_TAG_PREFIX='master'
            else
                BRANCH_TAG_PREFIX='branch'
            fi
            echo "export IMAGE_NAME=startmeapp-hackathon-front" >> $BASH_ENV
            echo "export IMAGE_TAG=${BRANCH_TAG_PREFIX}-${SHORT_COMMIT_HASH}" >> $BASH_ENV

      - run:
          name: Build docker image
          command: |
            docker build --build-arg API=$API_MAPS -t angulito/$IMAGE_NAME:$IMAGE_TAG -t angulito/$IMAGE_NAME:latest .

      - run:
          name: Push docker image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker push angulito/$IMAGE_NAME:$IMAGE_TAG
            docker push angulito/$IMAGE_NAME:latest

  deploy:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "startmeapp-hackathon"
      - GOOGLE_PROJECT_ID: "startmeapp-hackathon"
      - GOOGLE_COMPUTE_ZONE: "europe-west1-b"
      - GOOGLE_CLUSTER_NAME: "startmeapp-hackathon-cluster"
    steps:

      - checkout

      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}

      - run: 
          name: Deploy to Kubernetes
          command: |
            kubectl apply -f ./kubernetes/controller/app-controller.yaml
            kubectl apply -f ./kubernetes/service/app-service.yaml
            kubectl rollout status deployment.v1.apps/startmeapp-hackathon-app

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master