apiVersion: v1
kind: Service
metadata:
  name: startmeapp-hackathon-app
  labels:
    name: startmeapp-hackathon-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: startmeapp-hackathon-app